name: Update AbuseIPDB Blocklist

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to fetch IPs
        env:
          ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
        run: python scripts/abuseipdb_to_edl.py

      - name: Commit and push updated blocklist
        run: |
          git config user.name "AbuseIPDB Bot"
          git config user.email "bot@edl.io"
          git add blocklist.txt
          git commit -m "Update blocklist from AbuseIPDB"
          git push
